-- MySQL Script generated by MySQL Workbench
-- Fri Dec  6 20:50:27 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema salaosenac
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salaosenac
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salaosenac` DEFAULT CHARACTER SET utf8 ;
USE `salaosenac` ;

-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_cargo` (
  `cbo` VARCHAR(6) NOT NULL,
  `faixaSalarial` DECIMAL(10,2) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cbo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_funcionario` (
  `cpf` VARCHAR(11) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `estadoCivil` VARCHAR(45) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `nomeSocial` VARCHAR(45) NULL,
  `salario` DECIMAL(6,2) NOT NULL,
  `ch` DATETIME NOT NULL,
  `tbl_cargo_cbo` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_tbl_funcionario_tbl_cargo1_idx` (`tbl_cargo_cbo` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_funcionario_tbl_cargo1`
    FOREIGN KEY (`tbl_cargo_cbo`)
    REFERENCES `salaosenac`.`tbl_cargo` (`cbo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_profissional`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_profissional` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(250) NOT NULL,
  `especialidade` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `estadoCivil` VARCHAR(45) NOT NULL,
  `nomeSocial` VARCHAR(255) NULL,
  `dataNasc` DATE NOT NULL,
  `comissao` DECIMAL(6,2) NOT NULL,
  `salario` DECIMAL(6,2) NOT NULL,
  `sexo` CHAR(1) NOT NULL,
  `ch` TIME NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_dependente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_dependente` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `parentesco` VARCHAR(45) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `tbl_funcionario_cpf` VARCHAR(11) NOT NULL,
  `tbl_profissional_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `idtbl_dependenteFuncionario_UNIQUE` (`cpf` ASC) VISIBLE,
  INDEX `fk_tbl_dependenteFuncionario_tbl_funcionario_idx` (`tbl_funcionario_cpf` ASC) VISIBLE,
  INDEX `fk_tbl_dependente_tbl_profissional1_idx` (`tbl_profissional_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_dependenteFuncionario_tbl_funcionario`
    FOREIGN KEY (`tbl_funcionario_cpf`)
    REFERENCES `salaosenac`.`tbl_funcionario` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_dependente_tbl_profissional1`
    FOREIGN KEY (`tbl_profissional_cpf`)
    REFERENCES `salaosenac`.`tbl_profissional` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_ferias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_ferias` (
  `idtbl_ferias` INT NOT NULL AUTO_INCREMENT,
  `qtdDias` INT NOT NULL,
  `dataInicio` DATE NOT NULL,
  `dataFim` DATE NOT NULL,
  `tbl_funcionario_cpf` VARCHAR(11) NOT NULL,
  `tbl_profissional_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idtbl_ferias`),
  INDEX `fk_tbl_ferias_tbl_funcionario1_idx` (`tbl_funcionario_cpf` ASC) VISIBLE,
  INDEX `fk_tbl_ferias_tbl_profissional1_idx` (`tbl_profissional_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_ferias_tbl_funcionario1`
    FOREIGN KEY (`tbl_funcionario_cpf`)
    REFERENCES `salaosenac`.`tbl_funcionario` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_ferias_tbl_profissional1`
    FOREIGN KEY (`tbl_profissional_cpf`)
    REFERENCES `salaosenac`.`tbl_profissional` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_registroServico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_registroServico` (
  `idtbl_registroServico` INT NOT NULL,
  `nomeCliente` VARCHAR(45) NOT NULL,
  `valor` DECIMAL(6,2) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `data` DATETIME NOT NULL,
  `tbl_funcionario_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idtbl_registroServico`),
  UNIQUE INDEX `idtbl_registroServico_UNIQUE` (`idtbl_registroServico` ASC) VISIBLE,
  INDEX `fk_tbl_registroServico_tbl_funcionario1_idx` (`tbl_funcionario_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_registroServico_tbl_funcionario1`
    FOREIGN KEY (`tbl_funcionario_cpf`)
    REFERENCES `salaosenac`.`tbl_funcionario` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_telefone` (
  `idtbl_telefone` INT NOT NULL,
  `numero` VARCHAR(15) NOT NULL,
  `tbl_funcionario_cpf` VARCHAR(11) NOT NULL,
  `tbl_profissional_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idtbl_telefone`),
  UNIQUE INDEX `idtbl_telefone_UNIQUE` (`idtbl_telefone` ASC) VISIBLE,
  UNIQUE INDEX `tbl_telefonecol_UNIQUE` (`numero` ASC) VISIBLE,
  INDEX `fk_tbl_telefone_tbl_funcionario1_idx` (`tbl_funcionario_cpf` ASC) VISIBLE,
  INDEX `fk_tbl_telefone_tbl_profissional1_idx` (`tbl_profissional_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_telefone_tbl_funcionario1`
    FOREIGN KEY (`tbl_funcionario_cpf`)
    REFERENCES `salaosenac`.`tbl_funcionario` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_telefone_tbl_profissional1`
    FOREIGN KEY (`tbl_profissional_cpf`)
    REFERENCES `salaosenac`.`tbl_profissional` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_endereco` (
  `idtbl_endereco` INT NOT NULL AUTO_INCREMENT,
  `uf` CHAR(2) NOT NULL,
  `cidade` VARCHAR(200) NOT NULL,
  `bairro` VARCHAR(200) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `rua` VARCHAR(255) NOT NULL,
  `tbl_funcionario_cpf` VARCHAR(11) NOT NULL,
  `tbl_profissional_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idtbl_endereco`),
  UNIQUE INDEX `cep_UNIQUE` (`cep` ASC) VISIBLE,
  INDEX `fk_tbl_endereco_tbl_funcionario1_idx` (`tbl_funcionario_cpf` ASC) VISIBLE,
  INDEX `fk_tbl_endereco_tbl_profissional1_idx` (`tbl_profissional_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_endereco_tbl_funcionario1`
    FOREIGN KEY (`tbl_funcionario_cpf`)
    REFERENCES `salaosenac`.`tbl_funcionario` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_endereco_tbl_profissional1`
    FOREIGN KEY (`tbl_profissional_cpf`)
    REFERENCES `salaosenac`.`tbl_profissional` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_servico` (
  `idtbl_servico` INT NOT NULL AUTO_INCREMENT,
  `servicoPrestado` VARCHAR(200) NOT NULL,
  `tbl_registroServico_idtbl_registroServico` INT NOT NULL,
  `tbl_profissional_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idtbl_servico`),
  INDEX `fk_tbl_servico_tbl_registroServico1_idx` (`tbl_registroServico_idtbl_registroServico` ASC) VISIBLE,
  INDEX `fk_tbl_servico_tbl_profissional1_idx` (`tbl_profissional_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_servico_tbl_registroServico1`
    FOREIGN KEY (`tbl_registroServico_idtbl_registroServico`)
    REFERENCES `salaosenac`.`tbl_registroServico` (`idtbl_registroServico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_servico_tbl_profissional1`
    FOREIGN KEY (`tbl_profissional_cpf`)
    REFERENCES `salaosenac`.`tbl_profissional` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_cliente` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_cadastroCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_cadastroCliente` (
  `idtbl_cadastroCliente` INT NOT NULL AUTO_INCREMENT,
  `dataCadastro` DATETIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `tbl_cliente_cpf` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idtbl_cadastroCliente`),
  UNIQUE INDEX `idtbl_cadastroCliente_UNIQUE` (`idtbl_cadastroCliente` ASC) VISIBLE,
  INDEX `fk_tbl_cadastroCliente_tbl_cliente1_idx` (`tbl_cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_cadastroCliente_tbl_cliente1`
    FOREIGN KEY (`tbl_cliente_cpf`)
    REFERENCES `salaosenac`.`tbl_cliente` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_agendamento` (
  `idtbl_agendamento` INT UNSIGNED NOT NULL,
  `dia` DATE NOT NULL,
  `hora` DATETIME NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `tbl_cadastroCliente_idtbl_cadastroCliente` INT NOT NULL,
  PRIMARY KEY (`idtbl_agendamento`),
  INDEX `fk_tbl_agendamento_tbl_cadastroCliente1_idx` (`tbl_cadastroCliente_idtbl_cadastroCliente` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_agendamento_tbl_cadastroCliente1`
    FOREIGN KEY (`tbl_cadastroCliente_idtbl_cadastroCliente`)
    REFERENCES `salaosenac`.`tbl_cadastroCliente` (`idtbl_cadastroCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_itensServicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_itensServicos` (
  `tbl_agendamento_idtbl_agendamento` INT UNSIGNED NOT NULL,
  `tbl_servico_idtbl_servico` INT NOT NULL,
  `precoUnitario` DECIMAL(6,2) NOT NULL,
  `valorTotal` DECIMAL(6,2) NOT NULL,
  `desconto` DECIMAL(6,2) NOT NULL,
  `observacao` VARCHAR(200) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `quantidade` INT NOT NULL,
  INDEX `fk_tbl_agendamento_has_tbl_servico_tbl_servico1_idx` (`tbl_servico_idtbl_servico` ASC) VISIBLE,
  INDEX `fk_tbl_agendamento_has_tbl_servico_tbl_agendamento1_idx` (`tbl_agendamento_idtbl_agendamento` ASC) VISIBLE,
  PRIMARY KEY (`tbl_agendamento_idtbl_agendamento`, `tbl_servico_idtbl_servico`),
  CONSTRAINT `fk_tbl_agendamento_has_tbl_servico_tbl_agendamento1`
    FOREIGN KEY (`tbl_agendamento_idtbl_agendamento`)
    REFERENCES `salaosenac`.`tbl_agendamento` (`idtbl_agendamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_agendamento_has_tbl_servico_tbl_servico1`
    FOREIGN KEY (`tbl_servico_idtbl_servico`)
    REFERENCES `salaosenac`.`tbl_servico` (`idtbl_servico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`feedback` (
  `tbl_cliente_cpf` VARCHAR(11) NOT NULL,
  `tbl_servico_idtbl_servico` INT NOT NULL,
  `avaliacao` INT NOT NULL,
  `data_feedback` DATETIME NOT NULL,
  `experiencia` VARCHAR(250) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tbl_cliente_cpf`, `tbl_servico_idtbl_servico`),
  INDEX `fk_tbl_cliente_has_tbl_servico_tbl_servico1_idx` (`tbl_servico_idtbl_servico` ASC) VISIBLE,
  INDEX `fk_tbl_cliente_has_tbl_servico_tbl_cliente1_idx` (`tbl_cliente_cpf` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_cliente_has_tbl_servico_tbl_cliente1`
    FOREIGN KEY (`tbl_cliente_cpf`)
    REFERENCES `salaosenac`.`tbl_cliente` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_cliente_has_tbl_servico_tbl_servico1`
    FOREIGN KEY (`tbl_servico_idtbl_servico`)
    REFERENCES `salaosenac`.`tbl_servico` (`idtbl_servico`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salaosenac`.`tbl_venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salaosenac`.`tbl_venda` (
  `idtbl_venda` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(6,2) NOT NULL,
  `tbl_cadastroCliente_idtbl_cadastroCliente` INT NOT NULL,
  `tbl_agendamento_idtbl_agendamento` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idtbl_venda`),
  UNIQUE INDEX `idtbl_venda_UNIQUE` (`idtbl_venda` ASC) VISIBLE,
  INDEX `fk_tbl_venda_tbl_cadastroCliente1_idx` (`tbl_cadastroCliente_idtbl_cadastroCliente` ASC) VISIBLE,
  INDEX `fk_tbl_venda_tbl_agendamento1_idx` (`tbl_agendamento_idtbl_agendamento` ASC) VISIBLE,
  CONSTRAINT `fk_tbl_venda_tbl_cadastroCliente1`
    FOREIGN KEY (`tbl_cadastroCliente_idtbl_cadastroCliente`)
    REFERENCES `salaosenac`.`tbl_cadastroCliente` (`idtbl_cadastroCliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tbl_venda_tbl_agendamento1`
    FOREIGN KEY (`tbl_agendamento_idtbl_agendamento`)
    REFERENCES `salaosenac`.`tbl_agendamento` (`idtbl_agendamento`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
